services:
  backend:
    build:
      context: ./backend
    container_name: skufia-api
    ports:
      - "8007:8007"
    volumes:
      - ./backend:/app
      - skufia_uploads:/app/uploads
      - skufia_db:/app/data
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: skufia-web
    ports:
      - "5551:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx_full.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: always

volumes:
  skufia_uploads:
  skufia_db: