services:
  postgres:
    image: postgres:16
    container_name: skufia-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-skufia}
    volumes:
      - skufia_pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: skufia-redis
    restart: always

  celery:
    image: ghcr.io/${GHCR_USER:-up1t3}/skufia-backend:latest
    container_name: skufia-celery
    command: celery -A worker.celery_app worker --loglevel=info --concurrency=2
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-skufia}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
    depends_on:
      - postgres
      - redis
    volumes:
      - skufia_uploads:/app/uploads
      - skufia_db:/app/data
    restart: always

  coturn:
    image: coturn/coturn
    container_name: skufia-coturn
    restart: always
    network_mode: host
    command: >
      turnserver
      --lt-cred-mech
      --user=guest:guest_password
      --realm=skuf-net.ru
      --external-ip=147.45.245.133
      --listening-port=3478
      --min-port=49152
      --max-port=49252
      --no-tls
      --no-dtls
      --fingerprint
      --log-file=stdout
      --simple-log

  backend-blue:
    image: ghcr.io/${GHCR_USER:-up1t3}/skufia-backend:latest
    container_name: skufia-api-blue
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-skufia}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - postgres
      - redis
    volumes:
      - skufia_uploads:/app/uploads
      - skufia_db:/app/data
    restart: always

  backend-green:
    image: ghcr.io/${GHCR_USER:-up1t3}/skufia-backend:latest
    container_name: skufia-api-green
    ports:
      - "8008:8007"
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-skufia}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - postgres
      - redis
    volumes:
      - skufia_uploads:/app/uploads
      - skufia_db:/app/data
    restart: always

  frontend:
    image: ghcr.io/${GHCR_USER:-up1t3}/skufia-frontend:latest
    container_name: skufia-web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend-blue
      - backend-green
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend/upstream.conf:/etc/nginx/upstream.conf:ro
    restart: always

volumes:
  skufia_uploads:
  skufia_db:
  skufia_pgdata:
